DROP TABLE IF EXISTS campaigns;

CREATE TABLE campaigns (
    id SERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);